"""Preloaded Motor 01 historical events used by AERA's comparison engine."""
from __future__ import annotations

from typing import Any, Dict, List

HISTORY_EVENTS: List[Dict[str, Any]] = [
    {
        "event_number": 104,
        "timestamp": "2026-08-12T10:24:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "High vibration with rising temperature at elevated load.",
        "detected_anomaly": "High vibration + increasing temperature",
        "severity": "HIGH",
        "temperature": 87.0,
        "vibration": 6.9,
        "speed": 1412.0,
        "load": 82.0,
        "current": 13.8,
        "voltage": 231.0,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Checked bearing alignment and lubrication",
        "outcome": "Issue resolved. Vibration returned to 2.9 mm/s.",
        "resolution_minutes": 8,
        "what_happened": "Drive-end bearing lubrication was low. Alignment was slightly off.",
    },
    {
        "event_number": 109,
        "timestamp": "2026-07-28T14:11:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Vibration jumped while current and temperature climbed.",
        "detected_anomaly": "Bearing mechanical pattern",
        "severity": "HIGH",
        "temperature": 86.2,
        "vibration": 7.1,
        "speed": 1408.0,
        "load": 80.0,
        "current": 14.1,
        "voltage": 232.0,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Inspected bearing alignment. Reduced load to 60% until inspection complete.",
        "outcome": "Motor held until planned stop. Bearing packed and aligned.",
        "resolution_minutes": 7,
        "what_happened": "Misalignment at the coupling produced bearing load.",
    },
    {
        "event_number": 112,
        "timestamp": "2026-07-04T09:42:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Vibration 7.4 mm/s with thermal rise.",
        "detected_anomaly": "High vibration",
        "severity": "HIGH",
        "temperature": 88.0,
        "vibration": 7.4,
        "speed": 1402.0,
        "load": 84.0,
        "current": 14.6,
        "voltage": 230.8,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": True,
        "intervention": True,
        "operator_action": "Stopped motor per SOP-MTR-BRG-01. Drive-end bearing replaced.",
        "outcome": "Trip avoided after stop. Bearing replaced. Restored next shift.",
        "resolution_minutes": 11,
        "what_happened": "Drive-end bearing wear. Continued running would have tripped.",
    },
    {
        "event_number": 118,
        "timestamp": "2026-06-19T16:03:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Similar vibration/temperature pair during high load.",
        "detected_anomaly": "Mechanical vibration",
        "severity": "HIGH",
        "temperature": 85.4,
        "vibration": 6.8,
        "speed": 1416.0,
        "load": 79.0,
        "current": 13.5,
        "voltage": 232.2,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": False,
        "operator_action": "Monitored after a load reduction. Lubrication restored on the next stop.",
        "outcome": "Lubrication restored. Vibration settled in 6 minutes.",
        "resolution_minutes": 6,
        "what_happened": "Dry drive-end bearing under sustained load.",
    },
    {
        "event_number": 121,
        "timestamp": "2026-06-02T11:18:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Vibration with current rise. Speed droop.",
        "detected_anomaly": "Bearing drag",
        "severity": "HIGH",
        "temperature": 84.8,
        "vibration": 7.0,
        "speed": 1410.0,
        "load": 81.0,
        "current": 13.9,
        "voltage": 231.4,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Checked coupling and bearing alignment",
        "outcome": "Coupling bolts retightened. Condition cleared.",
        "resolution_minutes": 7,
        "what_happened": "Loose coupling hardware transferred misalignment into the bearing.",
    },
    {
        "event_number": 126,
        "timestamp": "2026-05-14T08:51:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "High vibration at 7.3 mm/s.",
        "detected_anomaly": "High vibration + temperature",
        "severity": "HIGH",
        "temperature": 86.8,
        "vibration": 7.3,
        "speed": 1405.0,
        "load": 83.0,
        "current": 14.2,
        "voltage": 231.6,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": True,
        "intervention": True,
        "operator_action": "Inspected bearing alignment. Motor stopped when vibration passed 8 mm/s.",
        "outcome": "Bearing replaced. Motor returned to normal.",
        "resolution_minutes": 9,
        "what_happened": "Late intervention. Bearing damage required replacement.",
    },
    {
        "event_number": 131,
        "timestamp": "2026-04-22T13:40:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Vibration rise that self-limited after load cut.",
        "detected_anomaly": "Vibration increase",
        "severity": "ATTENTION",
        "temperature": 79.0,
        "vibration": 5.6,
        "speed": 1428.0,
        "load": 76.0,
        "current": 12.4,
        "voltage": 232.0,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": False,
        "operator_action": "Reduced load and continued monitoring",
        "outcome": "No trip. Inspection scheduled. No failure.",
        "resolution_minutes": 4,
        "what_happened": "Load-related vibration. Did not develop into a bearing failure.",
    },
    {
        "event_number": 138,
        "timestamp": "2026-03-30T15:07:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_bearing_failure",
        "event_type": "motor_bearing_failure",
        "description": "Classic bearing pattern. Operator could not stop immediately.",
        "detected_anomaly": "High vibration while motor had to keep running",
        "severity": "HIGH",
        "temperature": 85.9,
        "vibration": 7.2,
        "speed": 1409.0,
        "load": 82.0,
        "current": 14.0,
        "voltage": 231.2,
        "trend": {"vibration": 1, "temperature": 1, "current": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Could not stop. Reduced load to 60%. Monitored vibration. Inspected at next safe stop.",
        "outcome": "Held safely until planned stop. Alignment corrected. No trip.",
        "resolution_minutes": 7,
        "what_happened": "Same pattern as now. Alternative path (load cut + deferred inspection) worked.",
    },
    {
        "event_number": 91,
        "timestamp": "2026-08-01T19:12:00",
        "machine": "MOTOR-01",
        "pattern_family": "voltage_spike",
        "event_type": "voltage_spike",
        "description": "Short incoming voltage spike. Other parameters unchanged.",
        "detected_anomaly": "Voltage spike",
        "severity": "NORMAL",
        "temperature": 62.4,
        "vibration": 2.8,
        "speed": 1450.0,
        "load": 64.0,
        "current": 10.2,
        "voltage": 251.0,
        "trend": {"voltage": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None. Event logged.",
        "outcome": "Self-cleared. No impact.",
        "resolution_minutes": 0,
        "what_happened": "Supply transient. Common on this motor.",
    },
    {
        "event_number": 92,
        "timestamp": "2026-07-21T03:44:00",
        "machine": "MOTOR-01",
        "pattern_family": "voltage_spike",
        "event_type": "voltage_spike",
        "description": "Voltage pulse, 2 seconds, returned to 232 V.",
        "detected_anomaly": "Voltage spike",
        "severity": "NORMAL",
        "temperature": 61.8,
        "vibration": 2.7,
        "speed": 1448.0,
        "load": 63.0,
        "current": 10.1,
        "voltage": 249.0,
        "trend": {"voltage": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No trip. No intervention.",
        "resolution_minutes": 0,
        "what_happened": "Harmless supply spike.",
    },
    {
        "event_number": 93,
        "timestamp": "2026-06-11T22:09:00",
        "machine": "MOTOR-01",
        "pattern_family": "voltage_spike",
        "event_type": "voltage_spike",
        "description": "Voltage excursion with stable mechanicals.",
        "detected_anomaly": "Voltage spike",
        "severity": "NORMAL",
        "temperature": 63.0,
        "vibration": 2.9,
        "speed": 1451.0,
        "load": 65.0,
        "current": 10.3,
        "voltage": 248.0,
        "trend": {"voltage": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Logged only.",
        "resolution_minutes": 0,
        "what_happened": "Repeated harmless voltage pattern.",
    },
    {
        "event_number": 94,
        "timestamp": "2026-05-03T06:28:00",
        "machine": "MOTOR-01",
        "pattern_family": "voltage_spike",
        "event_type": "voltage_spike",
        "description": "Another self-clearing voltage spike.",
        "detected_anomaly": "Voltage spike",
        "severity": "NORMAL",
        "temperature": 62.1,
        "vibration": 2.8,
        "speed": 1449.0,
        "load": 64.0,
        "current": 10.2,
        "voltage": 250.0,
        "trend": {"voltage": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No consequence.",
        "resolution_minutes": 0,
        "what_happened": "Same supply pattern as previous spikes.",
    },
    {
        "event_number": 71,
        "timestamp": "2026-08-08T12:02:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_cycle",
        "event_type": "temp_cycle",
        "description": "Temperature rose 3°C during a load cycle and returned.",
        "detected_anomaly": "Small temperature fluctuation",
        "severity": "NORMAL",
        "temperature": 65.0,
        "vibration": 2.8,
        "speed": 1446.0,
        "load": 70.0,
        "current": 10.8,
        "voltage": 232.0,
        "trend": {"temperature": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Normal load-cycle heating.",
        "resolution_minutes": 0,
        "what_happened": "Expected thermal drift with load. Repeated many times without consequence.",
    },
    {
        "event_number": 72,
        "timestamp": "2026-07-16T17:33:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_cycle",
        "event_type": "temp_cycle",
        "description": "Brief +3°C temperature rise.",
        "detected_anomaly": "Temperature fluctuation",
        "severity": "NORMAL",
        "temperature": 65.2,
        "vibration": 2.9,
        "speed": 1447.0,
        "load": 68.0,
        "current": 10.6,
        "voltage": 232.0,
        "trend": {"temperature": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Returned to 62°C. No action.",
        "resolution_minutes": 0,
        "what_happened": "Harmless operating-cycle temperature change.",
    },
    {
        "event_number": 73,
        "timestamp": "2026-04-09T10:15:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_cycle",
        "event_type": "temp_cycle",
        "description": "Temperature cycle during production peak.",
        "detected_anomaly": "Temperature fluctuation",
        "severity": "NORMAL",
        "temperature": 66.0,
        "vibration": 3.0,
        "speed": 1444.0,
        "load": 72.0,
        "current": 11.0,
        "voltage": 231.8,
        "trend": {"temperature": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No intervention required.",
        "resolution_minutes": 0,
        "what_happened": "Consistent with previous operating cycles.",
    },
    {
        "event_number": 81,
        "timestamp": "2026-06-26T09:20:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_overload",
        "event_type": "motor_overload",
        "description": "Current up, speed down, vibration stable.",
        "detected_anomaly": "Motor overload",
        "severity": "ATTENTION",
        "temperature": 74.0,
        "vibration": 3.2,
        "speed": 1398.0,
        "load": 92.0,
        "current": 15.1,
        "voltage": 230.5,
        "trend": {"current": 1, "load": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Reduced process load to 70%.",
        "outcome": "Current and speed recovered. No mechanical fault.",
        "resolution_minutes": 5,
        "what_happened": "Process demand, not a bearing issue.",
    },
    {
        "event_number": 82,
        "timestamp": "2026-05-20T18:47:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_overload",
        "event_type": "motor_overload",
        "description": "High load with current rise.",
        "detected_anomaly": "Overload",
        "severity": "ATTENTION",
        "temperature": 76.0,
        "vibration": 3.1,
        "speed": 1400.0,
        "load": 90.0,
        "current": 14.8,
        "voltage": 231.0,
        "trend": {"current": 1, "load": 1, "speed": -1},
        "failure": False,
        "intervention": True,
        "operator_action": "Confirmed process demand and reduced load.",
        "outcome": "Cleared without stop.",
        "resolution_minutes": 4,
        "what_happened": "Temporary high mechanical load.",
    },
    {
        "event_number": 61,
        "timestamp": "2026-03-08T11:55:00",
        "machine": "MOTOR-01",
        "pattern_family": "motor_overheat",
        "event_type": "motor_overheat",
        "description": "Thermal rise with restricted cooling.",
        "detected_anomaly": "Overtemperature",
        "severity": "HIGH",
        "temperature": 91.0,
        "vibration": 3.4,
        "speed": 1438.0,
        "load": 78.0,
        "current": 12.8,
        "voltage": 232.0,
        "trend": {"temperature": 1},
        "failure": False,
        "intervention": True,
        "operator_action": "Checked cooling path. Reduced load. Cleared fan inlet.",
        "outcome": "Temperature fell to 68°C.",
        "resolution_minutes": 10,
        "what_happened": "Blocked cooling inlet, not a bearing fault.",
    },
    {
        "event_number": 51,
        "timestamp": "2026-08-18T14:06:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "Temperature 85°C at 90% load. Vibration stayed normal.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 85.0,
        "vibration": 3.1,
        "speed": 1432.0,
        "load": 90.0,
        "current": 14.4,
        "voltage": 231.0,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None. Continued monitoring.",
        "outcome": "Temperature settled as load eased. No intervention.",
        "resolution_minutes": 0,
        "what_happened": "Expected heating at high process load.",
    },
    {
        "event_number": 52,
        "timestamp": "2026-07-09T11:22:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "85°C during a production peak at 88% load.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 84.6,
        "vibration": 3.0,
        "speed": 1436.0,
        "load": 88.0,
        "current": 14.1,
        "voltage": 232.0,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No fault. Common operating point.",
        "resolution_minutes": 0,
        "what_happened": "Temperature follows load on this motor.",
    },
    {
        "event_number": 53,
        "timestamp": "2026-06-01T16:40:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "86°C at 92% load, vibration 3.2 mm/s.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 86.0,
        "vibration": 3.2,
        "speed": 1428.0,
        "load": 92.0,
        "current": 14.7,
        "voltage": 230.8,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Resolved with load, not a mechanical inspection.",
        "resolution_minutes": 0,
        "what_happened": "Repeated high-load thermal pattern without failure.",
    },
    {
        "event_number": 54,
        "timestamp": "2026-04-27T09:15:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "Temperature 85°C, load 90%, vibration normal.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 85.2,
        "vibration": 2.9,
        "speed": 1430.0,
        "load": 90.0,
        "current": 14.3,
        "voltage": 231.5,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No intervention required.",
        "resolution_minutes": 0,
        "what_happened": "Consistent with previous high-load cycles.",
    },
    {
        "event_number": 55,
        "timestamp": "2026-03-12T13:48:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "84°C at 91% load during a long production run.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 84.0,
        "vibration": 3.0,
        "speed": 1431.0,
        "load": 91.0,
        "current": 14.5,
        "voltage": 231.2,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Temperature followed load. No inspection required.",
        "resolution_minutes": 0,
        "what_happened": "Common high-load heating on Motor 01.",
    },
    {
        "event_number": 56,
        "timestamp": "2026-02-02T08:11:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "85°C, 89% load, vibration 3.1 mm/s.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 85.4,
        "vibration": 3.1,
        "speed": 1433.0,
        "load": 89.0,
        "current": 14.2,
        "voltage": 232.1,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None. Continued monitoring.",
        "outcome": "No intervention. Condition is expected at this load.",
        "resolution_minutes": 0,
        "what_happened": "Repeated operating point with no mechanical fault.",
    },
    {
        "event_number": 57,
        "timestamp": "2026-01-19T19:04:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "High-load thermal rise, vibration remained normal.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 83.8,
        "vibration": 2.8,
        "speed": 1435.0,
        "load": 87.0,
        "current": 13.9,
        "voltage": 231.8,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "Returned with load. Logged only.",
        "resolution_minutes": 0,
        "what_happened": "Temperature tracks process load on this motor.",
    },
    {
        "event_number": 58,
        "timestamp": "2025-12-08T10:55:00",
        "machine": "MOTOR-01",
        "pattern_family": "temp_high_load",
        "event_type": "temp_high_load",
        "description": "86°C at 93% load. No vibration rise.",
        "detected_anomaly": "High-load heating",
        "severity": "ATTENTION",
        "temperature": 86.2,
        "vibration": 3.3,
        "speed": 1426.0,
        "load": 93.0,
        "current": 14.9,
        "voltage": 230.4,
        "trend": {"temperature": 1, "load": 1},
        "failure": False,
        "intervention": False,
        "operator_action": "None",
        "outcome": "No stop. Production continued.",
        "resolution_minutes": 0,
        "what_happened": "Expected thermal behaviour at peak load.",
    },
]


def history_resolutions() -> List[Dict[str, Any]]:
    out = []
    for event in HISTORY_EVENTS:
        if not event.get("intervention"):
            continue
        out.append(
            {
                "created_at": event["timestamp"],
                "pattern_family": event["pattern_family"],
                "root_cause": event.get("what_happened"),
                "solution": event.get("operator_action"),
                "actions_taken": event.get("operator_action"),
                "result": event.get("outcome"),
                "verified": True,
            }
        )
    return out


def average_resolution_minutes(family: str) -> float:
    times = [
        float(event["resolution_minutes"])
        for event in HISTORY_EVENTS
        if event.get("pattern_family") == family and event.get("intervention")
    ]
    if not times:
        return 0.0
    return round(sum(times) / len(times), 1)
