"""Structured motor knowledge used by AERA. This is domain knowledge, not live data."""
from __future__ import annotations

from typing import Any, Dict, List

MOTOR_IDENTITY = {
    "code": "MOTOR-01",
    "tag": "M01",
    "name": "Motor 01",
    "type": "Three-phase induction motor with VFD",
    "location": "Drive end of Production Line 01",
    "principles": [
        "Speed is set by drive frequency. Loaded speed sits slightly below the setpoint.",
        "Current is proportional to torque demand. Current rising while speed falls usually means extra mechanical load or friction.",
        "Temperature rises gradually with load and operating time. A fast rise at unchanged load is abnormal.",
        "Vibration is low and stable in healthy bearings. A rising vibration trend with current and temperature is a mechanical warning.",
        "Voltage is a supply/drive condition. A short spike that returns to baseline is often harmless on this motor.",
        "Power is the product of voltage and current (and drive efficiency). Energy accumulates with runtime.",
    ],
}

# Contextual expected-value models: value ≈ intercept + load_gain * load + speed_gain * (speed/setpoint)
# These are used to ask "is this unusual for the current situation?" not only "is it above a fixed line?"
PARAMETERS: Dict[str, Dict[str, Any]] = {
    "speed": {
        "name": "Speed",
        "unit": "RPM",
        "meaning": "Rotational speed of the motor shaft.",
        "normal_behaviour": "Holds near the 1450 RPM setpoint in RUNNING. Small droop with load is expected.",
        "warning_behaviour": "Sustained droop of more than about 3% at unchanged setpoint.",
        "critical_behaviour": "Speed collapsing while the drive is still commanding run — likely overload or trip impending.",
        "relationships": ["Current rises as speed falls under load.", "Vibration and temperature often rise if the droop is mechanical."],
        "possible_causes": ["Mechanical overload", "Bearing drag", "Coupling resistance", "Drive limit"],
        "recommended_checks": ["Confirm speed setpoint", "Check mechanical load", "Check current and vibration together"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 1450.0,
        "load_gain": -0.35,
        "speed_gain": 0.0,
        "warn_pct": 0.04,
        "crit_pct": 0.08,
        "direction_bad": "down",
    },
    "speed_setpoint": {
        "name": "Speed setpoint",
        "unit": "RPM",
        "meaning": "Speed the drive is commanded to hold.",
        "normal_behaviour": "Stable operator/process setpoint, typically 1450 RPM on Motor 01.",
        "warning_behaviour": "Setpoint far from actual speed while the motor is RUNNING.",
        "critical_behaviour": "Drive cannot follow setpoint and a fault is active.",
        "relationships": ["Actual speed should track setpoint in RUNNING."],
        "possible_causes": ["Operator change", "Process recipe", "Drive limit"],
        "recommended_checks": ["Confirm commanded speed on the HMI"],
        "sop": "SOP-MTR-STR-01",
        "baseline": 1450.0,
        "load_gain": 0.0,
        "warn_pct": 0.1,
        "crit_pct": 0.2,
        "direction_bad": "either",
    },
    "current": {
        "name": "Current",
        "unit": "A",
        "meaning": "Stator current. Proxy for torque and mechanical demand.",
        "normal_behaviour": "Around 10.2 A at typical 64% load. Rises smoothly with load.",
        "warning_behaviour": "Unusually high for the current load, or rising while speed is falling.",
        "critical_behaviour": "Approaching thermal/overload protection with a worsening trend.",
        "relationships": ["High current with falling speed suggests overload or mechanical drag.", "High current with high temperature is a thermal risk."],
        "possible_causes": ["Increased mechanical load", "Bearing problem", "Low voltage", "Winding issue"],
        "recommended_checks": ["Check mechanical load", "Compare with speed and vibration", "Check voltage"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 10.2,
        "load_gain": 0.055,
        "warn_pct": 0.12,
        "crit_pct": 0.28,
        "direction_bad": "up",
    },
    "voltage": {
        "name": "Voltage",
        "unit": "V",
        "meaning": "Supply / drive output voltage.",
        "normal_behaviour": "Around 232 V with small fluctuation. Short spikes that self-clear are common on this motor.",
        "warning_behaviour": "Sustained deviation from the 228–235 V running band.",
        "critical_behaviour": "Voltage remaining far outside band with current/speed effects.",
        "relationships": ["A brief spike with unchanged current, speed, and vibration is usually supply noise."],
        "possible_causes": ["Incoming supply spike", "Drive DC bus transient", "Sensor noise"],
        "recommended_checks": ["Confirm duration", "Check whether current/speed moved", "Check other motors on the same supply"],
        "sop": "SOP-MTR-VLT-01",
        "baseline": 232.0,
        "load_gain": 0.0,
        "warn_pct": 0.05,
        "crit_pct": 0.1,
        "direction_bad": "either",
    },
    "frequency": {
        "name": "Frequency",
        "unit": "Hz",
        "meaning": "Drive output frequency. For this 4-pole motor, frequency ≈ speed / 30.",
        "normal_behaviour": "Near 48.3 Hz when speed is 1450 RPM.",
        "warning_behaviour": "Frequency and speed diverge, or frequency ramps unexpectedly.",
        "critical_behaviour": "Drive frequency collapse while RUN is still commanded.",
        "relationships": ["Frequency and speed should move together.", "Current inrush is expected during a frequency ramp at start."],
        "possible_causes": ["Drive ramp", "Setpoint change", "Drive fault"],
        "recommended_checks": ["Compare frequency with speed", "Check drive status"],
        "sop": "SOP-MTR-STR-01",
        "baseline": 48.33,
        "load_gain": 0.0,
        "warn_pct": 0.05,
        "crit_pct": 0.1,
        "direction_bad": "down",
    },
    "power": {
        "name": "Power",
        "unit": "kW",
        "meaning": "Electrical power drawn by the motor.",
        "normal_behaviour": "Around 2.4 kW at typical load. Tracks current and voltage.",
        "warning_behaviour": "Power rising without a corresponding process demand.",
        "critical_behaviour": "Power high enough to imply overload with rising temperature.",
        "relationships": ["Power ≈ voltage × current × efficiency.", "Energy is the integral of power."],
        "possible_causes": ["Load increase", "Mechanical friction", "Inefficient operating point"],
        "recommended_checks": ["Check load", "Check current and speed together"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 2.36,
        "load_gain": 0.02,
        "warn_pct": 0.18,
        "crit_pct": 0.35,
        "direction_bad": "up",
    },
    "torque": {
        "name": "Torque",
        "unit": "Nm",
        "meaning": "Estimated shaft torque from power and speed.",
        "normal_behaviour": "Stable for a given load. Rises if the process demands more force.",
        "warning_behaviour": "Torque rising while speed falls — extra mechanical resistance.",
        "critical_behaviour": "Torque demand beyond the motor’s normal band with thermal rise.",
        "relationships": ["Torque ≈ 9550 × kW / RPM.", "Current is the electrical counterpart of torque."],
        "possible_causes": ["Process load", "Binding", "Bearing drag"],
        "recommended_checks": ["Inspect connected mechanical load", "Check coupling"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 15.5,
        "load_gain": 0.12,
        "warn_pct": 0.18,
        "crit_pct": 0.35,
        "direction_bad": "up",
    },
    "load": {
        "name": "Load",
        "unit": "%",
        "meaning": "Mechanical/process load as a percentage of typical rated duty.",
        "normal_behaviour": "Typically 50–75% on this motor. 64% is the usual running point.",
        "warning_behaviour": "Sustained operation above about 88% without a known process reason.",
        "critical_behaviour": "Near 95% with rising current and temperature.",
        "relationships": ["Load sets the expected current, temperature, and torque."],
        "possible_causes": ["Process demand", "Restriction downstream", "Mechanical binding"],
        "recommended_checks": ["Confirm process demand", "Inspect driven equipment"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 64.0,
        "load_gain": 0.0,
        "warn_pct": 0.2,
        "crit_pct": 0.4,
        "direction_bad": "up",
    },
    "temperature": {
        "name": "Temperature",
        "unit": "°C",
        "meaning": "Motor thermal condition (frame/winding proxy).",
        "normal_behaviour": "Rises gradually with load and operating time. Around 62°C at typical 64% load.",
        "warning_behaviour": "Unusually high for the current load, or rising faster than expected.",
        "critical_behaviour": "Approaching thermal protection or continuing to climb with no load change.",
        "relationships": ["High load explains higher temperature.", "Temperature + vibration + current together is more serious than heat alone."],
        "possible_causes": ["Excessive load", "Cooling failure", "Bearing problem", "High ambient", "Mechanical friction"],
        "recommended_checks": ["Check load", "Check cooling path", "Check vibration", "Check bearings", "Check current"],
        "sop": "SOP-MTR-TMP-01",
        "baseline": 62.0,
        "load_gain": 0.18,
        "runtime_gain": 0.8,
        "warn_delta": 8.0,
        "crit_delta": 16.0,
        "direction_bad": "up",
    },
    "vibration": {
        "name": "Vibration",
        "unit": "mm/s",
        "meaning": "Mechanical vibration, typically drive-end bearing / housing.",
        "normal_behaviour": "Around 2.8 mm/s and stable in RUNNING. Startup can be briefly higher.",
        "warning_behaviour": "Rising trend or unusually high for the current speed/load.",
        "critical_behaviour": "Above about 8 mm/s or a steep multi-minute rise with current and temperature.",
        "relationships": ["Bearing wear: vibration ↑, current ↑, temperature ↑, speed ↓.", "Load-only events raise current more than vibration."],
        "possible_causes": ["Bearing wear", "Misalignment", "Unbalance", "Loose mounting", "High mechanical load"],
        "recommended_checks": ["Listen at the drive-end bearing", "Inspect coupling", "Check mounting bolts", "Compare with historical bearing incidents"],
        "sop": "SOP-MTR-BRG-01",
        "baseline": 2.8,
        "load_gain": 0.012,
        "warn_pct": 0.35,
        "crit_pct": 1.4,
        "direction_bad": "up",
    },
    "energy": {
        "name": "Energy",
        "unit": "kWh",
        "meaning": "Accumulated electrical energy since the Motor + HMI backend started.",
        "normal_behaviour": "Increases steadily while the motor runs. Rate matches power.",
        "warning_behaviour": "Energy rate much higher than usual for the same process output.",
        "critical_behaviour": "Not a trip parameter by itself; used as context.",
        "relationships": ["Energy is the integral of power."],
        "possible_causes": ["Longer runtime", "Higher load"],
        "recommended_checks": ["Compare power trend", "Compare load"],
        "sop": "SOP-MTR-OVL-01",
        "baseline": 0.0,
        "load_gain": 0.0,
        "warn_pct": 9.0,
        "crit_pct": 9.0,
        "direction_bad": "up",
    },
    "runtime": {
        "name": "Runtime",
        "unit": "h",
        "meaning": "Hours the motor has been running in this backend session.",
        "normal_behaviour": "Increases only while RUNNING/STARTING.",
        "warning_behaviour": "Very long continuous run may explain a slow temperature rise.",
        "critical_behaviour": "Not a trip parameter.",
        "relationships": ["Temperature may drift up slightly with runtime at constant load."],
        "possible_causes": ["Continuous operation"],
        "recommended_checks": ["Use as context for temperature, not as an alarm by itself"],
        "sop": "SOP-MTR-STR-01",
        "baseline": 0.0,
        "load_gain": 0.0,
        "warn_pct": 9.0,
        "crit_pct": 9.0,
        "direction_bad": "up",
    },
    "start_cycles": {
        "name": "Start/stop cycles",
        "unit": "count",
        "meaning": "Number of recorded start events.",
        "normal_behaviour": "Infrequent on a continuous line motor.",
        "warning_behaviour": "Repeated starts in a short period increase thermal and mechanical stress.",
        "critical_behaviour": "Start-on-fault or start into a mechanical bind.",
        "relationships": ["Startup current and vibration spikes are expected for a few seconds."],
        "possible_causes": ["Process stops", "Trips", "Operator starts"],
        "recommended_checks": ["Allow settle time after start before treating transients as faults"],
        "sop": "SOP-MTR-STR-01",
        "baseline": 12.0,
        "load_gain": 0.0,
        "warn_pct": 9.0,
        "crit_pct": 9.0,
        "direction_bad": "up",
    },
}

SITUATION_PATTERNS: List[Dict[str, Any]] = [
    {
        "id": "bearing_mechanical",
        "title": "DEVELOPING MECHANICAL / BEARING ISSUE",
        "family": "motor_bearing_failure",
        "signals": {"vibration": "up", "current": "up", "temperature": "up", "speed": "down"},
        "min_hits": 3,
        "sop": "SOP-MTR-BRG-01",
        "possible_cause": "Bearing wear or increasing mechanical drag at the drive end.",
        "consequence": "Continued running may raise temperature further and lead to an overload or bearing trip.",
        "checks": [
            "Check mechanical load and coupling for abnormal resistance.",
            "Inspect motor vibration at the drive-end bearing.",
            "Check bearing temperature/condition if safe to do so.",
            "Verify drive parameters and that the setpoint has not changed.",
            "If vibration continues increasing, stop the motor according to SOP-MTR-BRG-01 and escalate.",
        ],
        "avoid": [
            "Do not keep resetting a trip without inspection.",
            "Do not remove guards while the motor is running.",
            "Do not increase speed to 'push through' the load.",
        ],
    },
    {
        "id": "overload",
        "title": "DEVELOPING MOTOR OVERLOAD",
        "family": "motor_overload",
        "signals": {"current": "up", "speed": "down", "load": "up"},
        "min_hits": 3,
        "sop": "SOP-MTR-OVL-01",
        "possible_cause": "Increased mechanical load on the driven equipment.",
        "consequence": "Continued operation may increase motor temperature and lead to an overload trip.",
        "checks": [
            "Inspect the connected mechanical load.",
            "Confirm process demand has actually increased.",
            "Check current versus speed together.",
            "If load is normal, inspect bearing condition next.",
        ],
        "avoid": ["Do not raise the speed setpoint to compensate.", "Do not ignore a rising temperature once current is high."],
    },
    {
        "id": "overheat",
        "title": "MOTOR THERMAL RISE",
        "family": "motor_overheat",
        "signals": {"temperature": "up"},
        "min_hits": 1,
        "sop": "SOP-MTR-TMP-01",
        "possible_cause": "High load, cooling restriction, or developing mechanical friction.",
        "consequence": "Thermal protection may operate if the rise continues.",
        "checks": ["Check load", "Check cooling path and fan", "Compare with current and vibration"],
        "avoid": ["Do not spray water on an energized motor.", "Do not ignore a continuing climb."],
    },
    {
        "id": "voltage_transient",
        "title": "SUPPLY VOLTAGE TRANSIENT",
        "family": "voltage_spike",
        "signals": {"voltage": "up"},
        "min_hits": 1,
        "sop": "SOP-MTR-VLT-01",
        "possible_cause": "Incoming supply or drive bus spike.",
        "consequence": "Often none if it self-clears and other parameters stay normal.",
        "checks": ["Confirm the spike duration", "Check whether current, speed, and vibration moved"],
        "avoid": ["Do not treat a one-second spike as a mechanical failure."],
    },
    {
        "id": "startup",
        "title": "STARTUP TRANSIENT",
        "family": "startup_transient",
        "signals": {"current": "up", "speed": "up"},
        "min_hits": 1,
        "sop": "SOP-MTR-STR-01",
        "possible_cause": "Expected inrush while the motor is starting.",
        "consequence": "Should settle within about 20 seconds in a healthy start.",
        "checks": ["Allow the start to settle", "Abort if the motor does not reach speed"],
        "avoid": ["Do not declare a bearing fault in the first few seconds of STARTING."],
    },
]


def expected_value(name: str, load: float, speed: float, runtime_h: float) -> float:
    spec = PARAMETERS.get(name)
    if not spec:
        return 0.0
    base = float(spec.get("baseline") or 0.0)
    if name == "temperature":
        # 62°C is normal at ~64% load. Lower load should be cooler.
        return 50.5 + 0.18 * load + min(4.0, runtime_h * float(spec.get("runtime_gain") or 0.8))
    if name == "current":
        return 6.7 + 0.055 * load
    if name == "vibration":
        return 2.0 + 0.012 * load + max(0.0, (speed - 1450.0) * 0.001)
    if name == "speed":
        return float(spec.get("baseline") or 1450.0) - 0.35 * max(0.0, load - 64.0)
    if name == "torque":
        return 8.0 + 0.12 * load
    if name == "power":
        return 0.9 + 0.023 * load
    return base


def parameter_brief(name: str) -> Dict[str, Any]:
    spec = PARAMETERS.get(name) or {}
    return {
        "name": spec.get("name", name),
        "unit": spec.get("unit", ""),
        "meaning": spec.get("meaning", ""),
        "normal_behaviour": spec.get("normal_behaviour", ""),
        "warning_behaviour": spec.get("warning_behaviour", ""),
        "critical_behaviour": spec.get("critical_behaviour", ""),
        "relationships": spec.get("relationships", []),
        "possible_causes": spec.get("possible_causes", []),
        "recommended_checks": spec.get("recommended_checks", []),
        "sop": spec.get("sop"),
    }
